"""Add prescription entries table

Revision ID: b824cd4a4c1d
Revises: 4466eebf2e74
Create Date: 2025-06-15 14:39:13.629714

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b824cd4a4c1d"
down_revision = "4466eebf2e74"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prescription_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("health_record_id", sa.Integer(), nullable=False),
        sa.Column("medicine", sa.String(length=200), nullable=False),
        sa.Column("strength", sa.String(length=100), nullable=True),
        sa.Column("morning", sa.String(length=50), nullable=True),
        sa.Column("noon", sa.String(length=50), nullable=True),
        sa.Column("evening", sa.String(length=50), nullable=True),
        sa.Column("bedtime", sa.String(length=50), nullable=True),
        sa.Column("duration", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["health_record_id"],
            ["health_records.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("prescription_entries")
    # ### end Alembic commands ###
